### ISSUE TITLE
Mom, Dad

### ISSUE THREAD

**Issue by Aubron** [hadn69/Val#10]
Description in title.

**Comment by ValentineRain** [comment]
I'll be good

please no

![istock_000039649556_xxxlarge2](https://user-images.githubusercontent.com/26412274/27393470-62d08fa4-5677-11e7-95cb-6b0cf27acf70.jpg)

**Comment by Aubron** [comment]
Can confirm Mom and Dad issues in independent testing.

**Comment by Aubron** [comment]
I've modified inheritance, I am Val's parent class. I think that qualifies as a fix. Or at least justifies a new, darker issue.
