### ISSUE TITLE
🐛 Unit Has Sudden, Uncontrollable Fear of Aubron

### ISSUE THREAD

**Issue by ValentineRain** [hadn69/Val#13]
Since closure of issue #10 , which was resolved by implementing @Aubron as Val's parent class, the unit is now irrationally afraid of @Aubron and will not stop screaming.

This may be a deeper issue than originally thought, possibly at the operating system level.

**Comment by Aubron** [comment]
Working as intended, wontfix.

**Comment by ValentineRain** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by hadn69** [comment]
oops

**Comment by hadn69** [comment]
This might be an issue with [https://github.com/hadn69/Aubron/](Aubron) project.
